### ISSUE TITLE
crackwatcher.com

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#1034]
#### 🖥️ Browser
Chrome (126.0.0.0)
#### 📝 Reason
It takes a little while. But the cookie Pop-Up comes. After couple of seconds.
#### 🔗 URL
https://crackwatcher.com/
#### 🏷️ Version
7.3.0

**Comment by wanhose** [comment]
Same as #992.

**Comment by sonnyxq** [comment]
@wanhose Hi there :)

After the cookie popup is hidden... this little button at the left side appears:

![Screenshot 2024-10-06 201035](https://github.com/user-attachments/assets/c622ecb8-2ef6-431e-a61f-70490c7d611c)

with which you can edit or modify the dialog.
I strong believe it should also be hidden.
Because clicking on it doesn't do anything.
Because the cookie window is invisible - to edit the cookie dialog.

![Screenshot 2024-10-06 193214](https://github.com/user-attachments/assets/71cbc8e1-bed3-4e91-935c-2238ec5df762)

**Comment by wanhose** [comment]
> @wanhose Hi.
> 
> After the cookie popup is hidden... this little button at the left side appears. ... with which you can edit or modify the dialog. I strong believe it should also be hidden. Because clicking on it doesn't do anything. Because the cookie window is invisible - to edit the cookie dialog.
> 
> ![Screenshot 2024-10-06 232831](https://private-user-images.githubusercontent.com/60904977/373981245-3e3f4dcd-954b-4451-8386-5483b6290c2e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMDA2NDEsIm5iZiI6MTcyODMwMDM0MSwicGF0aCI6Ii82MDkwNDk3Ny8zNzM5ODEyNDUtM2UzZjRkY2QtOTU0Yi00NDUxLTgzODYtNTQ4M2I2MjkwYzJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDExMjU0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0NzY4NWI5N2ZiZGQ5MWExOWRiZTVkNmMwMGYwOTE1MWNmNWJkY2EzMThkY2MyOWZlNTczMTBhYmRhYjc5ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.L6bbmJfmPVNz6W0Tci7udpU-92Bi2vIfMZK-X08UjPM)

Hi @sonnyxq,

Please, update to database version `>= 1728300083309`.

Thanks!
