### ISSUE TITLE
Report for one domain (www.bahn.de) was re-opening a report for a completely different domain (www.city-bahn.de).

### ISSUE THREAD

**Issue by dreirund** [wanhose/cookie-dialog-monster#1124]
Ahoj,

there was [a report for the domain "www.city-bahn.de"](https://github.com/wanhose/cookie-dialog-monster/issues/706#issue-2432514656). It [was closed](https://github.com/wanhose/cookie-dialog-monster/issues/706#issuecomment-2267433809).

Later, someone else did submit a report for the domain "www.bahn.de", but [that report was appended to the report for "www.city-bahn.de"](https://github.com/wanhose/cookie-dialog-monster/issues/706#issuecomment-2364561698). This is wrong. They are completely unrelated domains and websites.

Regards!

**Comment by wanhose** [comment]
> Ahoj,
> 
> there was [a report for the domain "www.city-bahn.de"](https://github.com/wanhose/cookie-dialog-monster/issues/706#issue-2432514656). It [was closed](https://github.com/wanhose/cookie-dialog-monster/issues/706#issuecomment-2267433809).
> 
> Later, someone else did submit a report for the domain "www.bahn.de", but [that report was appended to the report for "www.city-bahn.de"](https://github.com/wanhose/cookie-dialog-monster/issues/706#issuecomment-2364561698). This is wrong. They are completely unrelated domains and websites.
> 
> Regards!

Ahoj @dreirund,

It turns out this was a bug that had been around for a few months, result of one of the limitations in the GitHub API, which unfortunately doesn't support exact-match searching. Instead, it requires pulling a list of issues, iterating through them, and selecting the relevant one... a tedious process!

But thanks to your report, we were able to identify and address this important issue.

Thanks again for helping us improve! 💯
