### ISSUE TITLE
seirsanduk.net

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#210]
## Specifications
- <b>Reason:</b> Page contains visual glitches
- <b>URL:</b> https://www.seirsanduk.net/
- <b>User-Agent:</b> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.5359.125 Safari/537.36
- <b>Version:</b> 6.2.3

**Comment by wanhose** [comment]
Can't reproduce this issue on my end, please feel free to open again this issue adding more information and steps to reproduce it. Thanks anyway for your contribution.

**Comment by Rusenche** [comment]
@wanhose 

I was able to reproduce the problem!

I show with a photo:

https://i.postimg.cc/V6HdHK0Z/AAAAAAAAAA.png

![AAAAAAAAAA](https://user-images.githubusercontent.com/18578128/232567591-de32e7ab-166c-4cd0-b419-2bc4bbcc6c13.png)

What I have enclosed in the red rectangle is a clip. But with the "Cookie dialog monster" extension enabled - the clip is impossible to play. It's impossible. I found that even if the extension is turned off from its button - it still doesn't work. The only solution is to exclude the extension altogether from chrome://extensions/ - I mean disable it. Only then is the clip previewed. I have no idea why if the extension stops working for this site only, that's not enough, the extension needs to be disabled.

The other thing is that the clip needs to be turned on and the subtitles on it, because the subtitles show a password that is applied to the field that I indicated in the above picture with an arrow.

Actually your "Cookie dialog monster" extension should undergo a drastic improvement even for this site https://www.seirsanduk.net/ as long as the extension button to turn it off for this site only has no positive reaction.

It is absurd to think that only by disabling the extension, the clip will be able to be turned on and watched. But it's a fact and you really need to seriously improve the extension.

You might have to open this thread because I see it's closed and moved elsewhere.

Read my analysis again to reproduce it exactly.

:}

**Comment by wanhose** [comment]
Hi @Rusenche,

Thanks for the explanation and also for the steps to reproduce the problem. I'm working on it to include this fix in the next major update scheduled in a few days. I'll keep you posted with more updates.

**Comment by wanhose** [comment]
Hi again,

The `6.3.0` update is out, it is under review by Google and Microsoft but will be published soon. Take a look from time to time to see if you can update and then let me know if this issue is solved as it is on my side.

Have a good day!

**Comment by Rusenche** [comment]
With the new version 6.3.0, the problem mentioned in the topic **is not solved**.

_Unfortunately, there is no change._

If the extension is turned off for https://www.seirsanduk.net/ - no change.

Again the extension must be disabled to preview the clip.

You need to make adjustments to the extension.

**I don't think you have tested this site with version 6.3.0.**

**Comment by wanhose** [comment]
I always test what I do. Check if you have ad blocker extensions or whatever on your side because it's working on my side:

<img width="1235" alt="image" src="https://user-images.githubusercontent.com/50265843/233052738-9f4e9409-4ca2-4cec-8b54-8335b1f554ef.png">

As before when I was solving this problem I needed to disable my ad blocker extension too because if you don't do it there's the following problem:

<img width="2299" alt="image" src="https://user-images.githubusercontent.com/50265843/233053024-c396af31-1b3d-421d-925c-da9c7a30494d.png">

Even if you have or not Cookie Dialog Monster extension enabled (please, see the color):

<img width="2298" alt="image" src="https://user-images.githubusercontent.com/50265843/233053278-89eadf05-29ad-4b9b-bbf3-80d449196cd5.png">

As summary, this page is working very bad like in this case if you refresh bypassing the cache very fast:

<img width="2274" alt="image" src="https://user-images.githubusercontent.com/50265843/233054447-6b1bbace-210b-4b3f-a9af-240baa0c8c71.png">

Even if we uninstall the extension at all:

<img width="2368" alt="image" src="https://user-images.githubusercontent.com/50265843/233055590-ffdb8d17-a122-4eb4-a068-7085afda3aba.png">

So I recommend you to [refresh the page bypassing the cache](https://www.howtogeek.com/672607/how-to-hard-refresh-your-web-browser-to-bypass-your-cache/) when you see that error or in the last case, uninstall the extension if it doesn't work for you because of only this page. 

Anyway, after a second attempt to see what's happening there and see that this page isn't working well by itself with or without Cookie Dialog Monster extension installed, I'm going to close this issue and mark it as `Won't fix`.

Thanks anyway for your contribution and have a good day.

**Comment by Rusenche** [comment]
When I wrote that the problem is not resolved with the new version, I meant exactly that. It doesn't matter if there is an ad blocker or not. It doesn't address the issue because I clearly wrote that the clip above is not previewed and that in order to preview the clip, the extension with version 6.3.0 must be disabled in order to preview the clip. After starting the clip, the subtitles are turned on, wait a bit and a password appears in the clip, which is filled in the field below.

I show with a photo:

https://i.postimg.cc/QdgFzWVT/lKnn.png

![lKnn](https://user-images.githubusercontent.com/18578128/233062394-a913a2f4-d262-40e5-b296-66b5f6e1839a.png)

As you can see from the picture - the ad blocker has no effect.

When the password is written in the field - the upper window with the clip disappears and the lower window is played/on.

https://i.postimg.cc/Gt0BNPPv/pass.png

![pass](https://user-images.githubusercontent.com/18578128/233062586-4bdb4436-5656-4f0b-803f-42ab828ddb89.png)

From what I can see in your pictures, the clip that is at the top is not displayed.

Here's what I mean you don't have above:

https://i.postimg.cc/QdgFzWVT/lKnn.png

![lKnn](https://user-images.githubusercontent.com/18578128/233062358-097e427e-0995-451f-85df-5217f5146bc8.png)


I'm assuming you have some other ad blocking extensions and/or DNS and/or a modified host file if the clip I circled in red doesn't appear.

Maybe to make it easier - test with a VPN and the clip should be viewable for you.

**Comment by wanhose** [comment]
Understood. Will do it as soon as possible, which country?

**Comment by Rusenche** [comment]
I tested it with USA VPN and with UK VPN.

:}
