### ISSUE TITLE
After updating...

### ISSUE THREAD

**Issue by M1Aston** [wanhose/cookie-dialog-monster#25]
After each CDM-update, all websites where it was disabled (because it broke\breaks something) have it enabled again.
Well, that was a clumsy way of saying that individual website settings are lost after each update.

By the way, here is a thought\suggestion. Would it be possible or useful to have some indication of when CDM is active on a website? Pop-up, different colour for the icon or some information in the drop-down menu. I think it would make diagnosing problematic websites somewhat easier.

**Comment by wanhose** [comment]
Hey @M1Aston,

You are right, we set this behaviour a few versions ago because we were constantly changing cache structure and it was easier to remove your cache than check if it was valid for a specific version.

We are going to remove this behaviour in the next update because we found a stable point in the road map.

About your suggestion, you can see when the extension is working or not looking the icon. You can pin the extension to easily see the current state:

- Not pinned:

![image](https://user-images.githubusercontent.com/50265843/140659051-550dcf63-968d-467c-8757-795bdca61daa.png)

- Pinned:

![image](https://user-images.githubusercontent.com/50265843/140659062-f5412563-ac2f-4498-a14c-9cb1df10b809.png)

- Not working (several reasons... blocked by the page, disabled by you or disabled by us due incompatibilities):

![image](https://user-images.githubusercontent.com/50265843/140659184-7dee3258-ae43-4b91-83c7-1828b1249d17.png)

- Working (or at least trying to work 😂):

![image](https://user-images.githubusercontent.com/50265843/140659159-8e0e97f6-0ee5-4a77-957a-1d47fd5b1fef.png)

Thank you for your feedback!

**Comment by wanhose** [comment]
Hey @M1Aston,

You are right and we are going to remove this behaviour in the next update because we are in a stable stage at the moment. We set this behaviour a few versions ago because we were constantly changing cache structure and it was easier to remove your cache than check if it was valid for a specific version.

About your suggestion, you can see when the extension is working or not looking the icon. You can pin the extension to easily see the current state:

- Not pinned:

![image](https://user-images.githubusercontent.com/50265843/140659051-550dcf63-968d-467c-8757-795bdca61daa.png)

- Pinned:

![image](https://user-images.githubusercontent.com/50265843/140659062-f5412563-ac2f-4498-a14c-9cb1df10b809.png)

- Not working (several reasons... blocked by the page, disabled by you or disabled by us due incompatibilities):

![image](https://user-images.githubusercontent.com/50265843/140659184-7dee3258-ae43-4b91-83c7-1828b1249d17.png)

- Working (or at least trying to work 😂):

![image](https://user-images.githubusercontent.com/50265843/140659159-8e0e97f6-0ee5-4a77-957a-1d47fd5b1fef.png)

Thank you for your feedback!

**Comment by wanhose** [comment]
Hey again @M1Aston, can you confirm if this problem persists after updating to **5.4.0**?

**Comment by M1Aston** [comment]
No, it seems to be working fine now. I have done a quick test with some websites where it had to be disabled. and so far so good. 
Thanks for the quick update.

**Comment by wanhose** [comment]
Fantastic, thank you too much @M1Aston 🙂
