### ISSUE TITLE
Update addon on addons.mozilla.org (version 5.5.5 from year 2022 is available there), or what is the reason that it is not updated?

### ISSUE THREAD

**Issue by dreirund** [wanhose/cookie-dialog-monster#558]
[At addons.mozilla.org, the current version of this addon available](https://addons.mozilla.org/en-US/firefox/addon/cookie-dialog-monster) is version 5.5.5.

This is a notification that it is out of date and a request to keep it updated.

I [further read](https://www.cookie-dialog-monster.com/#downloads)

> *[Due to technical issues with the Firefox Team, our extension's support on Mozilla Add-ons has ended with version 5.5.5.](https://www.cookie-dialog-monster.com/#downloads)*

Other extensions also manage to keep updated. So if this is not possible here, can you at least say what the issue is?

I am reluctant of installing addon from some random source.

Regards and thanks for the addon!

**Comment by wanhose** [comment]
Hi @dreirund,

Due to technical issues with the Firefox Team, our extension's support on Mozilla Add-ons has ended with version 5.5.5. However, you can still run a development copy of the last version of the extension. Steps for this are available in [our GitHub repository](https://github.com/wanhose/cookie-dialog-monster/tree/main/packages/browser-extension#installation-for-mozilla-firefox-and-non-listed-browser-users).

We appreciate your understanding and patience.

**Comment by dreirund** [comment]
Can you elaborate more details what "technical issues with the Firefox
Team" mean?

For me it has some sort of touch "this addon might have trackers or
other things in it that is intimidating on users", which actually holds
me back from installing it directly from here instead from
addons.mozilla.org.

So, can you make transparent or link to the relevant discussion why
your extension's support on Mozilla Add-ons ended with version 5.5.5?

**Comment by wanhose** [comment]
> Can you elaborate more details what "technical issues with the Firefox Team" mean? For me it has some sort of touch "this addon might have trackers or other things in it that is intimidating on users", which actually holds me back from installing it directly from here instead from addons.mozilla.org. So, can you make transparent or link to the relevant discussion why your extension's support on Mozilla Add-ons ended with version 5.5.5?

The discussion was in their private groups, so I can't directly link the conversation in here. I wouldn't have any problem in sharing it otherwise. In another hand, you can review the code you are downloading so you can be sure there are no "trackers or other things" in it as it isn't a package (just a .zip and you can inspect all the files).

Briefly summarizing the conversation we had, I lost the access to my account due 2FA. They didn't intend to help nor give reasonable options. So, I don't agree with their policies and we don't work together anymore.

If your question was answered, please I suggest you to close the issue. Sorry for the inconveniences.

**Comment by dreirund** [comment]
> *Briefly summarizing the conversation we had, I lost the access to my account due 2FA. They didn't intend to help nor give reasonable options. So, I don't agree with their policies and we don't work together anymore.*

Thank you!
