### ISSUE TITLE
etsy.com

### ISSUE THREAD

**Issue by M1Aston** [wanhose/cookie-dialog-monster#642]
https://www.etsy.com

This issue was closed last week, but unfortunately the cookie message still pops up.

**Comment by wanhose** [comment]
Hey @M1Aston,

Thanks for reporting the issue. It's weird because for me it's working, can you check if you have the extension enabled in this page?

![image](https://github.com/user-attachments/assets/0f01d20d-8ba3-4f87-a312-9b24aea6cc3d)

As you can see, for me it's already fixed showing 3 items blocked in this page. Have you fully reloaded your browser/rebooted your computer since I closed the issue past week?

If this doesn't help you, can you attach here the entire page HTML. You can easily download it right clicking somewhere in the page and pressing the option "Save as...".

Have a nice evening! 😄

**Comment by M1Aston** [comment]
Well, it seems to be working now. I don't know why it didn't before.
Sorry about the report.

**Comment by wanhose** [comment]
Don't worry. Feel free to reopen this issue if it still happens randomly after upgrading to `7.1.0`. Have a good day! 🌞
