### ISSUE TITLE
[Feature request] add possibility to add notes and screenshots anonymously, in reporting dialogue.

### ISSUE THREAD

**Issue by dreirund** [wanhose/cookie-dialog-monster#691]
When one reports a website through the addon and wants to add details, one has to reply to the github issue, thus revealing publicly the personal browsing preferences (since the URLs of the reported websites are in the issues) (besides the requirement to have a github account).

So I have the following feature request:

* Add the possibility to add comments from inside the addon's report dialogue,
* add the possibility to add screenshots from inside the addon's report dialogue.

Regards!

**Comment by wanhose** [comment]
Hi @dreirund,

This is really important, it has the highest priority for the next release.

Will keep you posted, thanks for the feedback! 💯

**Comment by wanhose** [comment]
This task is scheduled for the next major release, version `7.2.0`, which will be available on September 1st 📅

**Comment by wanhose** [comment]
Hi guys,

One day before... this feature is ready, so please update (or wait a bit to get the update automatically, if you have installed this extension through some store because is under review) to the latest `7.2.0`.

FYI, to include screenshots privately you will need to upload the screenshot to some hosting and then add this URL to the reason. Add file handling is a big implementation that should be done carefully, so let's iterate on this.

Thanks for your big contribution, more privacy from now on! 🕵️

**Comment by dreirund** [comment]
> *this feature is ready*

Great!
