### ISSUE TITLE
iot.maxfone.it

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#818]
#### Browser
Firefox (129.0)
#### Reason
Page contains visual glitches
#### URL
https://iot.maxfone.it/devices
#### Version
7.1.4

**Comment by edo2313** [comment]
**_It's not a public website._**
I reported it, it removes the dark "background" when you open a modal and also it makes it impossible to close them when clicking outside (I think that's because the click listener is on the background). I can provide some screenshots if needed or the HTML for the modal.
Thanks!

**Comment by wanhose** [comment]
> **_It's not a public website._** I reported it, it removes the dark "background" when you open a modal and also it makes it impossible to close them when clicking outside (I think that's because the click listener is on the background). I can provide some screenshots if needed or the HTML for the modal. Thanks!

Hi @edo2313,

Thanks for your first issue and welcome to the project. I've tried to register but there's no way, right? So please, can you share the HTML sending me an email to hello@wanhose.dev (in case there's some private data in the page that you don't want to share)?

Remember to have turned on the extension when exporting the HTML file to see what's affected by the extension.

Sorry for the delay, I've been very busy lately 😓

**Comment by edo2313** [comment]
Seems like the extension is adding a `display: none` to the standard bootstrap modal background:
`<div class="modal-backdrop fade show" style="display: none;"></div>`

I checked and the bug is present in the [Bootstrap documentation](https://getbootstrap.com/docs/5.3/components/modal/#examples), just click the **Launch demo modal** button and see the difference

**Comment by wanhose** [comment]
> Seems like the extension is adding a `display: none` to the standard bootstrap modal background: `<div class="modal-backdrop fade show" style="display: none;"></div>`
> 
> I checked and the bug is present in the [Bootstrap documentation](https://getbootstrap.com/docs/5.3/components/modal/#examples), just click the **Launch demo modal** button and see the difference

Hi again @edo2313,

To solve many issues in many many many pages where they build this cookie consent dialogs using Bootstrap, we decided to hide them all. Bring them back will break many pages, more than fix them IMO.

Can you close the modal through the "x" close button? Or is it only closable through the transparent background?

It's a tradeoff for a better experience in general terms. But I can enable the background for that page only, if this is what you want (please note, if there's a cookie dialog on that page, there are many options that you will see a gray background then). So if you can close it using the "x", I suggest you to keep doing it or just disable the extension for this page.

Looking forward to read your answer 😄

**Comment by edo2313** [comment]
Understandable, I just added a few exclusions for the domains that I use.
Thanks anyway! (And by the way, the extension works great in all the other cases)
